export const colors = {
    forest:                  '#1CA184',
    obsidian:                '#080812',
    white:                   '#ffffff',
    menu:                    '#121223',
    lead:                    '#0F0F17',
    basalt:                  '#14141C',
    tungsten:                '#191923',
    pencil:                  '#23232D',
    pepper:                  '#373741',
    nickel:                  '#4B4B55',
    granite:                 '#5F5F69',
    concrete:                '#82828C',
    soapstone:               '#9B9BA5',
    marble:                  '#AFAFB5',
    chrome:                  '#CDCDD2',
    smoke:                   '#D7D7DB',
    chalk:                   '#E6E6E8',
    snow:                    '#F0F0F3',
    reddishPink:             '#ff2d55',
    meadow:                  '#20B796',
    garden:                  '#24CCA8',
    icon:                    '#414173',
    overlay:                 '#0F0F17',
    launchPad:               '#121223',
    error:                   '#FC374B',
    sky:                     '#007AFF',
    ocean:                   '#2387FB',
    orchid:                  '#6464DC',
    gold:                    '#FF9421',
    sun:                     '#FFD200',
    teal:                    '#00b1c0',
    java:                    '#10acbd'
};

export const fontWeight = {
  AvenirNextMedium :           '500',
  AvenirNextDemiBold :         '600',
  AvenirNextBold :             'bold',
}
